name = "sonteen-auth"
main = "src/index.js"
compatibility_date = "2026-10-01"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "sonteen-auth-db67"
database_id = "1c67b80a-695c-4067-9dff-66461290b5c8"
