name = "sonteen-auth"
main = "src/index.js"
compatibility_date = "2026-10-01"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "sonteen-auth-db"
database_id = "REPLACE_WITH_YOUR_D1_DATABASE_ID"
